name: EchoLogApp
options:
  bundleIdPrefix: com.echolog
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "15.0"
  
settings:
  SWIFT_VERSION: 5.9

targets:
  EchoLogApp:
    type: application
    platform: iOS
    sources:
      - path: Core
      - path: Features
      - path: EchoLogApp
      - path: Persistence
    info:
      path: EchoLogApp/Info.plist
      properties:
        CFBundleDevelopmentRegion: ja_JP
        CFBundleDisplayName: EchoLog
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocationWhenInUseUsageDescription: "メモに位置情報を付加するために使用します"
        NSMicrophoneUsageDescription: "音声メモを録音するために使用します"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    entitlements:
      path: EchoLogApp/EchoLogApp.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.echolog.app
      INFOPLIST_FILE: EchoLogApp/Info.plist
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_ENTITLEMENTS: EchoLogApp/EchoLogApp.entitlements
    dependencies: []

schemes:
  EchoLogApp:
    build:
      targets:
        EchoLogApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
